export const ACTION_GET_ALLCHARACTER = "GET_ALLCHARACTER";
export const ACTION_GET_ALLSPECIES = "GET_ALLSPECIES";
export const ACTION_GET_CHARACTERBYPAGE = "GET_CHARACTERBYPAGE";
export const ACTION_GET_CHARACTERBYNAME = "GET_CHARACTERBYNAME";
export const ACTION_GET_CHARACTERBYSPECIE = "GET_CHARACTERBYSPECIE";
export const ACTION_FILTERBYGENDER = "FILTERBYGENDER";
export const ACTION_FILTERBYSTATUS = "FILTERBYSTATUS";
